import Head from 'next/head'
/** @jsxImportSource @emotion/react */
import NavItem from './NavItem'
import { HeaderStyle } from './HeaderStyle'
import { faBars } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'


const Header = () => {
    return(
        <>
            <Head>
                <title>Anilist Apollo GraphQL</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header css={HeaderStyle.header}>
                <div css={HeaderStyle.headerContainer}>
                    <nav css={HeaderStyle.navContainer}>
                        <NavItem 
                            href="/"
                            label="Home"
                        />
                        <NavItem 
                            href="/collection"
                            label="Collection"
                        />
                    </nav>
                </div>
            </header>
        </>
    )
}

export default Header